bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
caption_extension = ".txt"
clip_skip = 1
dataset_config = "/home/djo/Code22/CSCI4366/stable-diffusion/config.toml"
dynamo_backend = "no"
enable_bucket = true
epoch = 6
gradient_accumulation_steps = 1
huber_c = 0.1
huber_schedule = "snr"
learning_rate = 1e-5
learning_rate_te = 1e-5
logging_dir = "/home/djo/Code22/CSCI4366/juneau-lora/log"
loss_type = "l2"
lr_scheduler = "cosine"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 160
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_timestep = 1000
max_token_length = 75
max_train_steps = 1600
metadata_author = "Dylan O'Neill"
min_bucket_reso = 256
mixed_precision = "fp16"
multires_noise_discount = 0.3
noise_offset_type = "Original"
optimizer_type = "Lion"
output_dir = "/home/djo/Code22/CSCI4366/juneau-lora/model"
output_name = "juneau-lora"
pretrained_model_name_or_path = "/home/djo/Code22/CSCI4366/stable-diffusion/cyberrealistic_v60.safetensors"
prior_loss_weight = 1
resolution = "512,768"
sample_prompts = "/home/djo/Code22/CSCI4366/juneau-lora/model/prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 2
save_model_as = "safetensors"
save_precision = "fp16"
train_batch_size = 6
train_data_dir = "/home/djo/Code22/CSCI4366/juneau-lora/img"
xformers = true
